In [2]:
import pandas as pd
import numpy as np
rna = pd.read_csv(
    "../data/raw/Gene_Expression_RNA/rnaseq_washu_fpkm_uq.v4.0.tsv.gz",
    sep="\t"
)
rna = rna.drop(['gene_id','gene_type','gene_status','havana_gene','full_length','exon_length','exon_num'],axis=1).set_index('gene_name')
print(rna.shape)
rna = np.log2(rna + 1)
rna

(60483, 108)

,C3L-00104,C3L-00365,C3L-00674,C3L-00677,C3L-01040,C3L-01043,C3L-01045,C3L-01046,C3L-01048,C3L-01049,...,C3N-03473,PT-NPJ7,PT-P44H,PT-QVJO,PT-R55F,PT-RN5K,PT-RU72,PT-UTHO,PT-WVLH,PT-Y8DK
gene_name,,,,,,,,,,,,,,,,,,,,,
DDX11L1,8.397765,0.000000,0.000000,8.313831,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,8.384608,9.952388,0.000000,0.000000,0.000000,7.566012
RP11-34P13.7,11.098802,9.476208,10.286903,11.850845,11.473733,8.118231,10.661000,10.903827,0.000000,8.804550,...,12.473013,12.721056,10.970726,12.971541,9.279916,12.121582,11.411988,12.633013,8.560136,8.780898
RP5-902P8.10,17.427519,16.943599,16.126187,17.122488,16.154873,16.123394,16.132161,16.735669,17.515696,16.858326,...,16.140731,16.211508,15.830628,16.634526,17.204289,17.533272,17.091493,16.748653,15.394219,16.123658
RP4-591L5.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SUGT1P2,15.843886,15.894383,15.382624,15.986201,15.282942,15.736517,15.443826,14.994537,15.616174,15.601336,...,15.569631,15.237777,14.644813,15.008945,15.544391,15.742375,15.115895,15.610202,13.109544,13.271938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AC104306.4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,10.779130,0.000000,0.000000,0.000000,10.713920,0.000000,0.000000,0.000000,9.906974
IGBP1P3,9.190888,10.051241,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,8.963636,11.028378,9.177714,9.163423,9.224038,0.000000,10.454965,8.357718
RPL30P4,13.359923,13.958306,12.600089,11.691068,0.000000,0.000000,12.559419,10.687542,11.781982,12.285643,...,12.787072,10.813360,11.547632,0.000000,12.346866,10.748150,11.808431,0.000000,12.040685,12.524927
CNOT10,17.243669,17.449933,17.123607,17.475797,17.029530,17.273031,17.166310,17.131816,17.280325,17.355853,...,17.621511,16.900654,16.413587,16.677696,16.709011,16.579353,16.732745,16.801273,16.545664,16.564374
CNOT10-AS1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [8]:
pro = pd.read_csv("../data/processed/de_proteome.csv").set_index("gene")
pro

          log2FC        pvalue  adjustedpvalue  -log(adjustedp)
gene
A1BG    1.751663  1.740332e-19    1.649829e-18        17.782561
A2M     1.446368  2.631714e-14    1.480730e-13        12.829524
AAAS    0.603250  5.753307e-08    1.502036e-07         6.823320
AACS   -0.747064  8.155613e-09    2.376589e-08         7.624046
AADAT  -1.181237  7.377722e-08    1.893361e-07         6.722767
...          ...           ...             ...              ...
ZXDC   -0.051378  8.127155e-01    8.287182e-01         0.081593
ZYG11B -0.642655  5.650706e-12    2.446680e-11        10.611423
ZYX     1.046176  1.121758e-11    4.672422e-11        10.330458
ZZEF1  -0.336327  7.618389e-07    1.707208e-06         5.767714
ZZZ3    0.321398  7.911902e-05    1.350082e-04         3.869640

[10409 rows x 4 columns]

In [11]:
proset = set(pro.index)
rnaset = set(rna.index)

common = proset & rnaset
print(common)
print(len(common))

{'FAM213A', 'STK17A', 'RBP1', 'GIMAP8', 'ARMC8', 'GNL3L', 'GNAL', 'VPS29', 'IPCEF1', 'CALM2', 'TCEAL5', 'ATF2', 'UQCR11', 'WDR48', 'SSSCA1', 'HLA-C', 'PM20D2', 'COL3A1', 'HSPB1', 'KLHL4', 'PIN1', 'EIF2AK1', 'CSF2RA', 'GORASP1', 'VIPAS39', 'FAM135A', 'FADS3', 'MRPL10', 'SYNPR', 'HSPBP1', 'MYCBP', 'TBC1D2', 'TMEM209', 'PAK3', 'TARBP2', 'TMEM248', 'LSM1', 'LGMN', 'SLC38A3', 'SNX21', 'GGT5', 'SPAG7', 'FKBP1B', 'VTN', 'ZER1', 'SLC2A13', 'POP4', 'E2F5', 'RAB40C', 'ENPP1', 'NUBPL', 'C1orf198', 'ANKRD45', 'RNASE3', 'SPDL1', 'PAF1', 'LIMK2', 'PPP2CA', 'SMIM15', 'UBQLN4', 'CDO1', 'DSG2', 'FSD1L', 'DEGS1', 'ARMCX5', 'GPD1', 'MATN2', 'USP40', 'TMEM167B', 'FAM98A', 'CRIP1', 'THG1L', 'DIS3L', 'EPS15', 'RELB', 'CREB5', 'APAF1', 'PPM1B', 'RUVBL2', 'MRI1', 'STARD7', 'DOK1', 'NAA16', 'PRKAR1A', 'ZMPSTE24', 'ZBTB16', 'LRRC8A', 'MIS12', 'SEZ6L', 'SOGA3', 'ANKIB1', 'SENP7', 'OLFML3', 'MRPS2', 'MRPS33', 'BBS2', 'NEURL4', 'THBS2', 'UBQLN2', 'TALDO1', 'OTUD6B', 'RNF113A', 'HBZ', 'FAM171A2', 'FAM193B', 'MTMR2', 'ZNF24', 'PRCC', 'SH2B1', 'HGH1', 'FEM1C', 'RBM42', 'ARPIN', 'CRY2', 'EFNB1', 'ASTN1', 'GLTP', 'SMARCE1', 'LACTB2', 'PANX1', 'TMED5', 'TMEM230', 'FLVCR1', 'ISG15', 'PLP2', 'YAF2', 'SLC6A1', 'TFAM', 'GSTA4', 'THADA', 'CHMP1B', 'KRT18', 'IK', 'SLC25A3', 'SRPK1', 'C8orf76', 'SMNDC1', 'P2RY12', 'PURA', 'HELLS', 'HAUS4', 'POC1B', 'DCAF16', 'RPF2', 'SMAD9', 'FAU', 'SPATS2', 'KIAA0319L', 'SEPT3', 'DAB2', 'IRF2', 'LEMD3', 'APBA2', 'DVL1', 'RPS3', 'SLC31A1', 'MTFR1L', 'TBC1D1', 'PLOD2', 'ELOVL2', 'FXN', 'MYO1F', 'RAD1', 'AHCYL1', 'DHFR', 'SNX16', 'TTC9', 'NPTX2', 'RAD51C', 'ATP1A2', 'IL1RAP', 'ETNPPL', 'ADAM9', 'LITAF', 'CDC27', 'ABCF2', 'LZTR1', 'KLHL29', 'HBB', 'NSFL1C', 'TTBK2', 'C19orf47', 'GNL3', 'NUDCD2', 'CTU1', 'ZNF687', 'WDYHV1', 'CARD16', 'SEC24D', 'TBC1D7', 'DDX47', 'SELP', 'KSR1', 'TMED7', 'NUP133', 'CWC25', 'DDX54', 'SND1', 'TGFB1', 'WNT5A', 'PLXNB2', 'NOS2', 'TFRC', 'SSX2IP', 'GPS2', 'PLP1', 'LTBP2', 'ATRN', 'KCNA3', 'NLRX1', 'SLC35B2', 'ATP11A', 'CYB5R1', 'GNG13', 'LONP1', 'AOAH', 'GLMP', 'CPT1C', 'GPATCH1', 'RCHY1', 'TIMM10B', 'CUEDC2', 'EIF4H', 'M6PR', 'NDUFC2', 'DFFA', 'HELZ2', 'TRAPPC4', 'PPP1R11', 'NAP1L5', 'ANGEL1', 'ATAD3B', 'TRIM27', 'COMMD5', 'STRADA', 'SARNP', 'DCP1B', 'DDT', 'KCNQ2', 'FKBP8', 'POTEJ', 'CCR1', 'GPN3', 'KIF13A', 'HPX', 'P4HTM', 'VAPA', 'MED21', 'SNX32', 'NAIP', 'ALDH1A1', 'LATS1', 'CHERP', 'LPGAT1', 'DAZAP2', 'PHKA2', 'HEXIM2', 'NHLRC2', 'F5', 'ARG1', 'PARP16', 'TPCN1', 'BRD7', 'CCDC136', 'TYROBP', 'CCDC43', 'MARS2', 'PUF60', 'HRC', 'AP3M1', 'ARL6IP4', 'BTBD11', 'GTF2F2', 'MRPS35', 'PHF11', 'ECI2', 'KDM3A', 'OSTM1', 'PPIG', 'PDE1A', 'CLEC3B', 'AES', 'ANP32A', 'NOL8', 'UNC13B', 'PPP2R2B', 'UBXN7', 'HSPA2', 'FZD1', 'EXOC7', 'POTEF', 'NSUN5', 'BHLHE41', 'GABPB2', 'RSPH1', 'STK32A', 'WDR11', 'RUFY2', 'ZFYVE19', 'TRIM28', 'MUSTN1', 'MYRIP', 'TMEM19', 'ZBTB18', 'STX1B', 'MYH10', 'TCEAL4', 'MRPL46', 'GPLD1', 'FAM107A', 'SIGLEC8', 'SLIRP', 'C7orf25', 'STX6', 'C4BPA', 'LZIC', 'ARHGAP18', 'RBM3', 'HLA-A', 'PCMTD1', 'RNASEL', 'AIFM3', 'MCM6', 'AGA', 'IDE', 'MT-ATP6', 'SESTD1', 'UTP18', 'ZNF593', 'VGF', 'SLC38A10', 'SPC25', 'TADA3', 'LRRC4B', 'CORO2A', 'KCTD12', 'PDCD4', 'GMPR2', 'ECHS1', 'ADCYAP1R1', 'MXRA7', 'CRTC2', 'HIST1H1B', 'DCP1A', 'HSD17B14', 'ZC3HAV1', 'SEPSECS', 'REPS1', 'MAP7', 'HNRNPC', 'MAST4', 'HNRNPH1', 'SLC32A1', 'SLC29A1', 'USP46', 'DNAJA2', 'PSMD3', 'TPX2', 'POTEI', 'SEZ6L2', 'ARPP21', 'PARD6A', 'FCN3', 'CNOT3', 'CAMK2G', 'RNASET2', 'SNRNP27', 'CDC42SE2', 'DNAJC9', 'ADSL', 'GRHPR', 'GRIA4', 'DHX40', 'MAPK11', 'TMEM206', 'FAM207A', 'PRKD1', 'PAPSS1', 'ZC3H14', 'CGGBP1', 'TTC1', 'CA2', 'QTRT1', 'TIA1', 'TMEM87A', 'PTPRN2', 'TDG', 'DSC2', 'ERMP1', 'GOLGA7B', 'MSL3', 'GGPS1', 'TMEM51', 'EIF4B', 'NFASC', 'PPP1R3D', 'USP5', 'DPYSL3', 'RXRA', 'SLC25A4', 'ADI1', 'COX11', 'RGMB', 'EIF4G2', 'SETD3', 'CFL2', 'CHML', 'ZBED3', 'FBXL19', 'POFUT1', 'LPIN1', 'FAF1', 'KIFC3', 'GJC2', 'PVR', 'FUCA1', 'LPCAT2', 'COMMD8', 'DCXR', 'ISOC1', 'SRPX2', 'RFTN1', 'KIF5A', 'ARHGEF12', 'LMNB2', 'FAM136A', 'MICU3', 'POMT2', 'UQCC2', 'EPHA7', 'GNG11', 'ZNF827', 'ARL2', 'WWC1', 'CTSL', 'TRAPPC2L', 'CACNB1', 'TCN1', 'ACOT13', 'PDGFC', 'FTO', 'LTN1', 'SMCO4', 'ZNF280D', 'MTA3', 'BCL2L13', 'HIBCH', 'TNC', 'OGDH', 'GNB5', 'COLGALT2', 'CTDSP2', 'ARIH2', 'SLC17A6', 'GPAM', 'YTHDC1', 'QDPR', 'GJA1', 'MRPS7', 'PPP2R3C', 'CMC2', 'ATP6V1G1', 'APRT', 'CLSTN1', 'VAC14', 'RASAL2', 'PXYLP1', 'STIM2', 'ASNA1', 'NPY', 'PNOC', 'KCTD9', 'EPHA4', 'PLEKHB1', 'NDUFB4', 'PMVK', 'WARS2', 'MID1', 'CENPN', 'FAM185A', 'SLC20A1', 'IFFO2', 'AMFR', 'EGR1', 'GIMAP1', 'PRKCQ', 'SF3B2', 'CHADL', 'IGF2BP3', 'HYI', 'NAALADL2', 'MAFF', 'LYST', 'DOCK2', 'RNPEP', 'CDK5', 'RAB30', 'TSC22D2', 'DNAJC16', 'CCNL1', 'NDUFAF1', 'ORC2', 'AP3M2', 'GMEB1', 'RIMS4', 'SASH3', 'JMJD4', 'SORT1', 'NNMT', 'SLIT1', 'CSE1L', 'ZBED8', 'CASC3', 'KCTD20', 'HILPDA', 'NHS', 'TSSC4', 'FAM3C', 'ICAM1', 'JOSD2', 'NETO2', 'PKIA', 'TYW3', 'KCNAB1', 'RPL22', 'GTF2F1', 'KCNIP2', 'ARL14EP', 'KLHL13', 'NUP205', 'NHEJ1', 'ECSIT', 'ZC3H10', 'KCNB1', 'MTMR1', 'VPS36', 'CENPF', 'EPHB2', 'DNLZ', 'MAP7D3', 'ATP1A3', 'C16orf86', 'SMARCA2', 'HERC5', 'NR3C1', 'RWDD2A', 'SDC2', 'CDKN2AIP', 'PTK7', 'CEP131', 'ERBB4', 'RAB33B', 'PKN1', 'EXOSC2', 'PPWD1', 'IPO5', 'CPEB3', 'COG7', 'CRYGS', 'NFKBIA', 'CDK5RAP1', 'CNOT11', 'CLCN7', 'PDCD2', 'MLST8', 'LECT2', 'AHSA1', 'TRHDE', 'SLC25A6', 'FGA', 'TESPA1', 'GNAI2', 'KLHL20', 'MED17', 'ZC4H2', 'NUP37', 'C18orf32', 'COL18A1', 'SNRPG', 'ORM2', 'CPNE8', 'ATP4A', 'HGFAC', 'TAX1BP1', 'TESK1', 'SLC7A14', 'COQ7', 'DHX34', 'CRHBP', 'NFKBIE', 'TSN', 'PJA2', 'STARD3NL', 'DPT', 'EIF3F', 'H3F3A', 'ZNF451', 'FNBP1L', 'LSM12', 'SESN3', 'NFAT5', 'SPRYD7', 'FOXP1', 'PRKCZ', 'NDUFAF2', 'IRF3', 'PNCK', 'OCIAD1', 'TMEM167A', 'PSMD6', 'FBXO9', 'CPNE1', 'DOCK5', 'NPRL3', 'GUK1', 'PORCN', 'LMTK3', 'LMAN2', 'EEF2K', 'COPZ2', 'SHMT2', 'RABL6', 'CASP3', 'MTOR', 'C5orf30', 'TBC1D13', 'OSTC', 'CYP7B1', 'HTRA2', 'STK11', 'DLG1', 'AKR1B1', 'KIFAP3', 'MT-ND1', 'RBM26', 'VPS11', 'TOR4A', 'RFTN2', 'GRIN2A', 'SIAH1', 'GLUD1', 'ITGA2', 'ADCY6', 'SELL', 'KCNA1', 'PTBP3', 'FBN2', 'RDX', 'SCYL2', 'PNPLA2', 'PLAA', 'MAP7D1', 'STX12', 'SUCO', 'ASH2L', 'CDK6', 'EXOSC8', 'COQ9', 'TRPS1', 'S1PR2', 'TCEANC2', 'FUCA2', 'AXIN1', 'MCM4', 'CLOCK', 'ORMDL1', 'LENG1', 'TRIP4', 'POSTN', 'LIMK1', 'ADPRH', 'DHRS1', 'SCRIB', 'PRMT9', 'CAB39', 'SEC14L2', 'TRIAP1', 'BCO1', 'MED15', 'C12orf43', 'C3orf14', 'RELL1', 'RBFOX3', 'SYDE1', 'ABL1', 'ARHGEF37', 'SCG3', 'RAD54L2', 'SLC6A7', 'APBB1', 'RHCE', 'MPP6', 'PDE4DIP', 'PPP1R14A', 'NPM3', 'RSBN1L', 'SLC33A1', 'SFPQ', 'RUFY1', 'CTSF', 'PCM1', 'ADAM12', 'WRB', 'SHANK1', 'RTCA', 'KCNJ4', 'EBAG9', 'PDHX', 'POLR3E', 'SCAMP2', 'LILRB2', 'CELF2', 'PELO', 'TTC5', 'AHDC1', 'TMEM205', 'TARBP1', 'MPRIP', 'EFNB3', 'GRIPAP1', 'IGFBP6', 'ATP1B1', 'RASSF8', 'LRRFIP1', 'FAM131B', 'DUSP23', 'SSBP4', 'ELAVL2', 'DAAM1', 'RPA3', 'ARMCX6', 'ZNF713', 'PHF20', 'ZNF711', 'CPTP', 'NDUFB5', 'UGGT1', 'ZC3H15', 'C9', 'LIPA', 'TUBGCP6', 'DHX37', 'NARS', 'ZNHIT3', 'FASTKD2', 'GOLGA3', 'ATPAF2', 'MPP7', 'TMEM173', 'HAPLN3', 'ENKD1', 'SMIM13', 'UBTD1', 'SCAMP3', 'CCDC85C', 'FAM114A1', 'NOTCH1', 'CTNNA3', 'FAM81A', 'KCND2', 'NUBP1', 'DDX5', 'FBXO10', 'ZC3HC1', 'AIFM1', 'MTERF3', 'VDAC2', 'LMO2', 'WTAP', 'EEA1', 'TMEM201', 'NRXN3', 'HMMR', 'MSH3', 'HLA-E', 'MCAM', 'SCUBE2', 'HSPA4L', 'CCNYL1', 'REPIN1', 'PBXIP1', 'PREX2', 'TRUB1', 'UBE2G1', 'TIMM50', 'TRAPPC8', 'EIF4A3', 'COL5A2', 'LCLAT1', 'HM13', 'PANK3', 'PCTP', 'PTK2', 'INTS12', 'CLTB', 'TYRO3', 'ATP11B', 'GPR108', 'BRWD1', 'HLA-DRB5', 'TCP1', 'EEF1B2', 'MEX3C', 'AIF1L', 'ZNHIT6', 'ITGA5', 'YTHDF1', 'SLC6A9', 'EIF2B2', 'PDK2', 'RING1', 'F8A2', 'XKR4', 'FAM50A', 'ESD', 'IMPA1', 'RDH10', 'B2M', 'POGZ', 'PEF1', 'SMIM12', 'PDIA3', 'DXO', 'PPM1K', 'CRELD1', 'LRFN5', 'MITD1', 'DTYMK', 'CD34', 'GOT2', 'DGKZ', 'C3AR1', 'KLF3', 'TMEM223', 'FAM219A', 'TTI1', 'PEG10', 'CRYBG3', 'GLIPR1', 'PTGES3', 'NECAB3', 'PTPRO', 'TPMT', 'BMP1', 'CNTROB', 'FPGS', 'YTHDF2', 'HERC2', 'PPP2R5B', 'RHBDF2', 'KANK3', 'STXBP4', 'SMYD5', 'DYNC1LI1', 'CEP78', 'ZNF302', 'ZKSCAN4', 'ZNF773', 'KIAA0040', 'TTC7B', 'MAP2', 'PRR36', 'ARMC10', 'HACE1', 'UTP3', 'TMEM14C', 'NAV3', 'C2orf72', 'ELANE', 'LAGE3', 'ASAP3', 'MRPL12', 'RSRC1', 'NFS1', 'DNM2', 'DPP10', 'BLOC1S1', 'VMP1', 'PRR3', 'YRDC', 'ZNF395', 'LACTB', 'CYR61', 'LRRC8D', 'SEC24A', 'DNAJC19', 'TEP1', 'NHSL1', 'RPL26', 'TMEM258', 'COL11A1', 'SETX', 'NSRP1', 'TRAK2', 'CLDN12', 'CBL', 'CDC123', 'KLF16', 'PRPF3', 'UROD', 'AGAP1', 'DPH6', 'GAPVD1', 'SAP30L', 'ZFYVE9', 'SACM1L', 'APC', 'MYO1D', 'SYNPO', 'EXOSC1', 'WASF3', 'RELA', 'CFB', 'CALB1', 'TNFRSF12A', 'HSPA13', 'TGFB3', 'SLC12A5', 'TTC3', 'DNAJC2', 'IMPDH1', 'RALYL', 'TMA16', 'TMEM231', 'EPRS', 'KIAA1191', 'MYH9', 'NDUFS3', 'PCGF6', 'TUBB', 'GLRX2', 'TRIM26', 'ATP13A4', 'CLIC6', 'GALC', 'PI4K2A', 'NFATC2', 'SF3A1', 'TDRP', 'DEFA4', 'RP9', 'SIRT3', 'ARL1', 'SRSF10', 'DERA', 'TTC31', 'FAM76A', 'EIF4E', 'TMEM199', 'SMPX', 'MEST', 'MLYCD', 'MR1', 'YES1', 'CYB5B', 'FZD3', 'ACSS1', 'RALB', 'SFXN4', 'CUTC', 'DNM1L', 'IMP4', 'APOC3', 'LPAR1', 'SH2D3C', 'LRFN3', 'KCNJ6', 'TAC3', 'METTL9', 'RALGAPA2', 'SRA1', 'ALDH9A1', 'PRKACB', 'IL17D', 'BCL6', 'CPQ', 'CHST14', 'CDK3', 'ZDHHC13', 'FAM114A2', 'ADAM23', 'ALG6', 'PRRT2', 'LIMD1', 'EFNA5', 'LMBRD2', 'JMJD8', 'MNS1', 'ARHGAP1', 'SARS', 'TBCE', 'TMEM106B', 'ZFPL1', 'ETFA', 'KPNB1', 'SNX29', 'ZNF706', 'FGFR1OP2', 'NUDT19', 'SEPT9', 'CAMKMT', 'EFHD1', 'NOSTRIN', 'GPN2', 'UHRF2', 'EIF4E3', 'COQ10A', 'KBTBD4', 'FAM198B', 'EPN2', 'ADAM11', 'PARP14', 'PCDH18', 'UQCRC1', 'LBP', 'LRWD1', 'USP34', 'CYBA', 'ARPC2', 'PDCL3', 'TPP1', 'ABCD1', 'KEL', 'OAS1', 'MRPS22', 'VARS2', 'ISLR', 'MFHAS1', 'PTRHD1', 'MARC1', 'SMOC2', 'FCF1', 'ANAPC5', 'RPS9', 'EIF5B', 'VPS8', 'GPR17', 'CAMK2B', 'ZDHHC3', 'HBP1', 'CRTAP', 'EWSR1', 'UBE2F', 'MRPL52', 'UBL5', 'ABCA5', 'ASXL2', 'RANBP6', 'CMTM3', 'EXOG', 'HDHD2', 'PHF23', 'KIFC2', 'DENR', 'ALDH3A1', 'MRPL18', 'ACOT1', 'WDR54', 'ZBTB47', 'MTHFS', 'ST14', 'ECD', 'NOV', 'SURF4', 'TOX2', 'CRYL1', 'GOLM1', 'EMILIN3', 'TMEM33', 'FKBP4', 'MED14', 'GNG7', 'CRIM1', 'CYFIP1', 'GBP7', 'MUM1', 'POLR3K', 'MMP15', 'STC2', 'FAM210B', 'CRP', 'TMEM87B', 'ANKRD63', 'ACYP1', 'FDPS', 'NMNAT2', 'STEAP2', 'DNAJC1', 'FNBP1', 'NAE1', 'PDGFRA', 'RPS6KA5', 'RBMS3', 'CD68', 'CDK19', 'ACTR6', 'ARG2', 'SRP72', 'DCUN1D4', 'NR2C2', 'TBC1D25', 'ACAA2', 'XPNPEP3', 'DARS', 'RBFOX1', 'ANKRD28', 'CKAP4', 'FLT1', 'C11orf96', 'SLITRK3', 'TUBB1', 'BOD1L1', 'HSPA8', 'KHSRP', 'FBN1', 'SLC6A15', 'VPS37B', 'CTGF', 'NECAB1', 'SPECC1', 'FLYWCH1', 'CDH6', 'TTC19', 'FUK', 'ARID5B', 'SLC9A9', 'RAB23', 'LRCH4', 'SPPL2B', 'CA8', 'RNF121', 'CTR9', 'SMIM8', 'NSMCE4A', 'CCT3', 'RHBDF1', 'MEF2D', 'PELP1', 'CSPP1', 'ERAP1', 'MRVI1', 'PPDPF', 'SPTY2D1', 'FARP2', 'SCAMP1', 'ELL', 'MLKL', 'TIAL1', 'IL6ST', 'SNX24', 'BARD1', 'POLR1B', 'EXOC3', 'CDK13', 'CYP1B1', 'MAPT', 'YBX1', 'MTRF1', 'NUMA1', 'SYT5', 'RELL2', 'PPTC7', 'ARNT2', 'MAP1B', 'MYO18A', 'PGAP3', 'NPC1', 'PRDX1', 'LARP6', 'TRAPPC12', 'AMBRA1', 'NBEAL1', 'CDKL5', 'C1QL3', 'C9orf64', 'NGFR', 'DIMT1', 'ACO2', 'SOX11', 'ANAPC13', 'ATF6', 'EPS8L2', 'CHCHD10', 'SOS1', 'GTF2H3', 'ZYG11B', 'EPM2AIP1', 'MT1F', 'CNOT7', 'MRPL51', 'ENO3', 'GCC1', 'MYO9B', 'POLD3', 'TMEM181', 'IPO4', 'SOCS6', 'ARPC1A', 'ACAD9', 'LRRC57', 'PLVAP', 'RUNDC3A', 'SEC22A', 'VPS13B', 'CASK', 'CNN1', 'TCTN3', 'ITGB2', 'PPM1A', 'C19orf53', 'TMEM100', 'TSPAN7', 'DNM1', 'IP6K2', 'AQP4', 'CTIF', 'EIF2B5', 'MRPL4', 'SRXN1', 'MED20', 'INPP5J', 'ISG20L2', 'GRM7', 'MTM1', 'PTPRC', 'GABRA2', 'KMT2B', 'RALBP1', 'C11orf68', 'CDH8', 'SCN1A', 'SMS', 'BAG5', 'MRS2', 'CACNA1A', 'SMG1', 'A2M', 'GIMAP1-GIMAP5', 'QKI', 'TMX3', 'LARP7', 'PHF10', 'SAT2', 'SERPINF2', 'EXOC8', 'PARD6B', 'CYTH3', 'YWHAB', 'IMP3', 'COA5', 'DLC1', 'PCDHGC4', 'TAPBPL', 'ENTPD3', 'MRPL30', 'FAM110B', 'NOP16', 'KLHL2', 'AMER2', 'CCNH', 'APOL2', 'SBDS', 'ZHX3', 'CFHR2', 'ZMYM3', 'SH3BGRL3', 'RIF1', 'SPEG', 'PGRMC2', 'AFTPH', 'PSMD9', 'PHKG2', 'TNRC6B', 'BCL2L1', 'WDR55', 'GPCPD1', 'SNX30', 'RPL8', 'LPCAT1', 'RBBP7', 'MPHOSPH6', 'MTTP', 'DHX33', 'MINOS1', 'HYAL2', 'MPC2', 'IGFALS', 'ASB13', 'MIF', 'NKAIN3', 'ORAI1', 'SBF1', 'ACTR3', 'JADE2', 'IQSEC3', 'OTUD4', 'POMGNT1', 'ACBD3', 'RB1CC1', 'TBC1D9', 'NYAP2', 'RNF7', 'PSMD11', 'MZT1', 'KDM1B', 'GALNT1', 'CCDC8', 'PEPD', 'FOXG1', 'SLC25A25', 'LCP2', 'ME1', 'ABHD17A', 'NOP9', 'CREBBP', 'CCDC93', 'SH3PXD2B', 'BAZ2B', 'ATXN7', 'ENPP5', 'MFN2', 'FAM169A', 'KPNA6', 'RAB11FIP3', 'TRABD', 'ATG9A', 'ACLY', 'ATP11C', 'RAB5C', 'URGCP', 'S1PR1', 'CNN3', 'RASGEF1A', 'INTS4', 'SNIP1', 'ACADVL', 'RAI14', 'TMCO1', 'EYA4', 'TRIM44', 'USP48', 'TTYH2', 'PDIA5', 'DNAJC6', 'HLA-DQB1', 'AP2M1', 'TMED8', 'EXOSC9', 'FBXL20', 'WDR35', 'APOBEC3G', 'BLOC1S6', 'RBMX', 'RAVER1', 'DGKA', 'SEMA6D', 'PARP4', 'WDR75', 'DCTN5', 'C8orf37', 'ENPP6', 'ADAM17', 'C3orf33', 'CARD6', 'NUPR1', 'RPS11', 'SENP5', 'ADPRHL1', 'PANK1', 'NDUFS2', 'STOM', 'TMEM245', 'UBE2K', 'AP4B1', 'DDX3Y', 'CACYBP', 'IGFBP5', 'BRINP2', 'C2orf76', 'TXNRD1', 'DNPH1', 'GAN', 'CAB39L', 'CLEC14A', 'CALCOCO2', 'KIAA1522', 'MCCC2', 'NDUFA2', 'SDF4', 'TIMELESS', 'NMT1', 'MIPEP', 'PFDN6', 'UBE2J2', 'EIF3J', 'MRPS24', 'MTSS1', 'NAA50', 'ZNF629', 'BCR', 'EEF1G', 'HTRA1', 'MAPKBP1', 'FGF12', 'TBC1D5', 'SMPD1', 'TMEM63A', 'MUT', 'VBP1', 'ARFGAP2', 'KDM2B', 'FBXW8', 'TRIM11', 'ING4', 'SPIRE1', 'ZMIZ1', 'JAG1', 'NAT10', 'TRMT1', 'RCC1', 'ABHD4', 'CHD7', 'RBM12', 'WDR59', 'AAGAB', 'YIPF5', 'BPI', 'ERCC3', 'MYD88', 'SLMAP', 'UACA', 'VAPB', 'UTP6', 'PAIP1', 'ALDH3B1', 'SMARCC2', 'STARD3', 'BOLA1', 'CBLL1', 'DPH2', 'CRISPLD1', 'IRF2BP1', 'HIST2H2AA4', 'PAIP2B', 'DENND2A', 'FNIP2', 'KPNA4', 'CORO2B', 'ATP6V1B2', 'PROM1', 'CYP4X1', 'C21orf2', 'YWHAQ', 'DMAP1', 'CD47', 'MB21D2', 'BICD2', 'PHGDH', 'KCNIP3', 'ACP6', 'KMT2E', 'RMDN2', 'ACAP3', 'BRD9', 'NECAP1', 'PADI2', 'RANBP10', 'CRKL', 'CDC37L1', 'FKBPL', 'NEK4', 'PITPNC1', 'IARS2', 'CXCL5', 'RPS15A', 'OBSL1', 'KLHDC3', 'SOX5', 'MRPL27', 'MMACHC', 'ABHD11', 'EIF4A2', 'GAL3ST4', 'TMEM159', 'WDR20', 'KLHDC4', 'FGD3', 'SUCLA2', 'POLL', 'MRPL41', 'ERC2', 'NDUFB8', 'SERPINC1', 'UNC119', 'DNAJC3', 'GNG3', 'S100A4', 'RNF145', 'RPRD1A', 'DMXL1', 'IL1RAPL1', 'CGNL1', 'GNA12', 'ABCB9', 'ANKRD40', 'TPP2', 'MCMBP', 'MSANTD3', 'ARHGEF17', 'PGLYRP1', 'PAG1', 'ARFGEF2', 'MED13', 'DENND1A', 'PPP3R1', 'RNF114', 'BPTF', 'RYR2', 'FAM20B', 'ENTPD1', 'NKIRAS2', 'FBLN7', 'PPP2R3A', 'FGFR1', 'NUDCD3', 'IFI27L2', 'ACP1', 'NDEL1', 'CISD2', 'GNG5', 'CTBP2', 'ZNF106', 'KIAA1549L', 'GARS', 'GSTM2', 'CAV1', 'NCK1', 'SDSL', 'GNPTAB', 'NGEF', 'APIP', 'DNAJC24', 'COX14', 'JAK2', 'MAPK8IP2', 'CHCHD2', 'DKK3', 'CTNNB1', 'PSPH', 'DNAL4', 'TGFBI', 'STAT5B', 'HNRNPA1', 'SYNRG', 'TIMMDC1', 'WDR62', 'DCBLD1', 'AKT1S1', 'TCN2', 'ERBB3', 'VSTM2A', 'GRAP', 'HAGHL', 'LRRC49', 'ADAM15', 'RNASE4', 'DZIP3', 'CDK14', 'NUP107', 'CLIP4', 'PHYKPL', 'DROSHA', 'TIMM21', 'GATAD2B', 'ARHGEF10L', 'ASMTL', 'NTMT1', 'ILDR2', 'THOP1', 'GPX1', 'CMIP', 'C6orf106', 'SRSF5', 'UBE2V2', 'SEMA6B', 'PGLS', 'ACY3', 'PPP3CB', 'CCAR2', 'C2CD5', 'RBMS2', 'TBC1D2B', 'SRRM1', 'ZNF276', 'GLDC', 'DSTYK', 'MRPS23', 'DARS2', 'RNF123', 'CEND1', 'FAM167A', 'OLFML2B', 'STX1A', 'MOSPD2', 'HMGCS1', 'NDOR1', 'CWF19L1', 'SLITRK2', 'HTATSF1', 'RCOR2', 'PDF', 'SLC7A6OS', 'NAB2', 'CBS', 'ZNF691', 'RGS7', 'ZPR1', 'ZNF384', 'PRKACA', 'INIP', 'STOX2', 'JMJD1C', 'ZFAND5', 'TMTC2', 'MAP4', 'PCDHGB1', 'ODF2', 'SIDT2', 'TLK1', 'CPS1', 'CHD1', 'MCCC1', 'BBS7', 'COL8A1', 'GGACT', 'KCNQ3', 'MEOX2', 'SHISA5', 'KRT2', 'AMACR', 'SYN2', 'EDIL3', 'ETV1', 'RASL12', 'ABCF1', 'ARFGAP1', 'GFAP', 'TPM3', 'NR3C2', 'GMIP', 'CASP10', 'ABCF3', 'VPS13D', 'MMGT1', 'MEGF9', 'GMPR', 'THRAP3', 'KHK', 'SH3GLB2', 'RBX1', 'CAMP', 'DCTN2', 'RHOC', 'ADAMTSL4', 'PRSS1', 'KIAA2013', 'HPS1', 'TSFM', 'VAV3', 'PSMC2', 'SELENBP1', 'FAM219B', 'STK39', 'TPD52', 'PNMA6A', 'COG8', 'C1orf174', 'MIS18A', 'LIN52', 'IGF2', 'PSMD13', 'ASCC1', 'DTNB', 'SCN8A', 'KLHL26', 'PLEKHM3', 'ELP5', 'SDHAF1', 'TNKS', 'TWSG1', 'VMA21', 'ACTL6B', 'DNAJC10', 'PGS1', 'ZFAND1', 'RSRC2', 'INAFM2', 'FRRS1L', 'WDR45B', 'SPTBN1', 'TCF20', 'TIMM22', 'GTPBP1', 'SPI1', 'MTIF2', 'UBAP1', 'ZCCHC24', 'ESAM', 'NDUFB7', 'FGFRL1', 'MRPS11', 'GNG2', 'ADAM10', 'SLC8A1', 'MFSD5', 'SYTL4', 'PWP1', 'SRRM2', 'BTF3L4', 'RNF220', 'COL4A3BP', 'PSMA5', 'SLC1A4', 'PFKP', 'DVL2', 'FAM19A2', 'UTP15', 'MAST2', 'COX6C', 'NDUFS1', 'CSK', 'VPS39', 'LDHD', 'ZBTB14', 'ZNF100', 'DPYSL2', 'SNAPC5', 'SCARB2', 'LAMTOR5', 'PRF1', 'CDKN2A', 'UBALD1', 'FOLR2', 'SNRNP70', 'PHC2', 'ALKBH1', 'BST2', 'BCAR3', 'VCPIP1', 'C1GALT1C1', 'MGAT2', 'ACYP2', 'TRIM5', 'C6', 'CAD', 'PEX10', 'GATB', 'CUL2', 'LZTFL1', 'MMS19', 'IQGAP3', 'MRPL39', 'LDLR', 'METTL7A', 'RBKS', 'KIF18B', 'ANKS6', 'DNAJA1', 'SLC22A18', 'GNL2', 'FCN1', 'KRT5', 'TRAPPC10', 'WDR76', 'CRTC1', 'LRIG2', 'TDRD3', 'CDC42SE1', 'PPIC', 'SRRT', 'NCK2', 'THOC1', 'POLA2', 'MED30', 'WDSUB1', 'NCAPG2', 'EIF5', 'NDUFAF5', 'PAPOLG', 'PLEKHG3', 'CORO7', 'VSNL1', 'DNAJC25-GNG10', 'SNX5', 'BAZ1A', 'KIAA1211L', 'PADI4', 'CXorf38', 'ITGB1BP1', 'FECH', 'TSPAN3', 'PPP6R1', 'ZBTB21', 'LYRM9', 'KLHL25', 'TRMT13', 'UBE2Q2', 'RPP25', 'OSMR', 'ICA1', 'PTGR1', 'LIMS1', 'FAM89B', 'ADSSL1', 'MTA2', 'PSMC6', 'MDH2', 'ALDH1L2', 'EMILIN2', 'MRPS27', 'MLLT6', 'SRSF3', 'CORO6', 'C1D', 'PSME1', 'PPP1R1B', 'MTMR7', 'KIAA0355', 'OFD1', 'CDH1', 'RNF141', 'LIPE', 'PODN', 'ACAD8', 'CNN2', 'FES', 'SERPING1', 'NUDT3', 'TMUB1', 'ATG4A', 'KIF3C', 'PGM2L1', 'CMTM4', 'ADAP2', 'ACIN1', 'MRPS34', 'GAS2', 'RRM2B', 'SCN3A', 'ATXN2', 'PDE7A', 'CDK5RAP2', 'MT2A', 'ATRNL1', 'FAM84B', 'MRPL43', 'PLAC9', 'TTC13', 'ZBTB8OS', 'NDUFA13', 'MAP6D1', 'RBM5', 'NUP153', 'SLC1A5', 'MILR1', 'CNKSR2', 'FLOT1', 'UQCRB', 'EZH1', 'LIMCH1', 'WAS', 'USB1', 'ETFDH', 'PTPN1', 'VRK3', 'F9', 'HMGB2', 'C18orf25', 'PRKDC', 'PNPT1', 'CES1', 'AHSG', 'ZNF579', 'FAT3', 'SNX19', 'CNR1', 'C15orf40', 'LZTS3', 'RB1', 'PPP4R4', 'HIST2H3A', 'EVI2B', 'CTH', 'CCT6A', 'RNASEH1', 'DEFA1B', 'FTSJ3', 'FYN', 'OSGEPL1', 'HMGB1', 'CAMSAP3', 'ATF7', 'CPNE6', 'BGN', 'VGLL4', 'MAP3K10', 'COLEC12', 'STX3', 'DGKI', 'RARS', 'PTPRK', 'CIZ1', 'PLEKHM1', 'ZEB2', 'CP', 'SCD5', 'FRS2', 'EFEMP2', 'SYNJ2BP-COX16', 'DNAJB9', 'NTN1', 'MCF2L', 'ALOX12', 'VCPKMT', 'C1orf131', 'HLA-DPA1', 'PCSK1', 'LYPD1', 'ALDH3A2', 'STMN4', 'PAWR', 'TRMT112', 'PCNA', 'PRKD2', 'RAB3D', 'HEXIM1', 'SFRP2', 'FAM160B1', 'IRGQ', 'PRPF40B', 'C6orf47', 'RACGAP1', 'GEMIN6', 'APOD', 'BUB3', 'EIF2AK2', 'PRKCA', 'RGS7BP', 'IGSF8', 'RGS6', 'ZBTB40', 'MYEF2', 'NES', 'ARC', 'RNF11', 'RTKN', 'ENTPD2', 'CA13', 'PJA1', 'CD3EAP', 'FLNA', 'SF1', 'INPP1', 'PRAM1', 'RRAGC', 'TSPAN6', 'MAF1', 'VCL', 'NLGN4X', 'ELP2', 'GORAB', 'GTF2A1', 'PRKAG2', 'CFH', 'LIN7A', 'LMO7', 'PCYT2', 'AVEN', 'KCNN3', 'WBP11', 'WDR82', 'APPBP2', 'MARCH5', 'MLF1', 'TOP2B', 'SNX10', 'PBX3', 'CYCS', 'NDUFAF6', 'CELF1', 'SALL1', 'COG6', 'UBFD1', 'PKP2', 'FKBP7', 'GRIA2', 'IFT46', 'OGFRL1', 'B4GALNT1', 'PML', 'GOT1', 'PLD3', 'ABLIM3', 'RAP1GAP2', 'SLC25A29', 'NT5C3A', 'PGGT1B', 'DAAM2', 'REL', 'AIDA', 'BSN', 'ARMC9', 'PF4V1', 'TBC1D20', 'CPNE5', 'ZHX2', 'MGMT', 'RPL9', 'SEMA5A', 'TPGS1', 'DLG3', 'MITF', 'COL28A1', 'OSGEP', 'CCDC106', 'SCAPER', 'DDX42', 'MAGI2', 'RPN2', 'CAMLG', 'KRT7', 'SMOC1', 'ADH5', 'SLC9A7', 'BTAF1', 'NAA38', 'PDXDC1', 'TBXAS1', 'MAG', 'APC2', 'LGALS8', 'S100A12', 'MLX', 'ID1', 'SHOC2', 'SLC24A2', 'TMCO3', 'RAB24', 'TRIM62', 'DEPDC5', 'ERRFI1', 'HNRNPDL', 'ISY1', 'ARSB', 'BRI3BP', 'FBXL8', 'RABL2A', 'VDAC1', 'NIPBL', 'DDX20', 'LIAS', 'CSNK1A1', 'A1BG', 'PKM', 'ENY2', 'EZR', 'TENM3', 'BRIX1', 'PIGS', 'JMJD6', 'UBL4A', 'PPIE', 'CCDC90B', 'PGD', 'CDYL2', 'NDE1', 'NOS1', 'AGPAT3', 'PALLD', 'CHSY1', 'FABP7', 'HCFC1', 'CX3CR1', 'HMBOX1', 'TUBA8', 'SH3PXD2A', 'DEK', 'OLIG1', 'FAF2', 'C12orf4', 'NAV2', 'ZNF2', 'ITGA1', 'HCCS', 'TCAIM', 'CCNT1', 'TP53RK', 'VPS37C', 'TXNRD2', 'ATP13A1', 'AKR1D1', 'PUSL1', 'TM9SF4', 'SUCLG1', 'UPF3A', 'TIMP2', 'PFKFB2', 'HAPLN2', 'TAGLN2', 'PAM', 'AP2S1', 'ARHGEF26', 'RGS17', 'PFAS', 'CARM1', 'KANSL3', 'KNOP1', 'SPARC', 'NCAN', 'B3GALT6', 'CUTA', 'SMG7', 'ZBTB1', 'HEXDC', 'HSD11B1', 'CARS', 'HIGD1A', 'DGCR2', 'PITHD1', 'GSTZ1', 'CXCL14', 'SLU7', 'FBXL3', 'ETNK1', 'F13B', 'GMDS', 'CRLS1', 'TUBB3', 'GLS', 'GAPDHS', 'TM9SF1', 'WRAP73', 'C5AR1', 'HOPX', 'SIL1', 'ARHGAP21', 'TBL2', 'CACFD1', 'SPPL2A', 'CLEC2L', 'QSOX2', 'JPH3', 'TRMT11', 'OSBPL11', 'RAB